LittlerootTown_House2_1F_MapScripts::
	.byte 0


LittlerootHouse2_1F_Mother::
# 6 "data/maps/LittlerootTown_House2_1F/scripts.pory"
	lock
# 7 "data/maps/LittlerootTown_House2_1F/scripts.pory"
	faceplayer
# 8 "data/maps/LittlerootTown_House2_1F/scripts.pory"
	msgbox LittlerootHouse2_1F_Mother_Text_0
# 9 "data/maps/LittlerootTown_House2_1F/scripts.pory"
	waitmessage
# 10 "data/maps/LittlerootTown_House2_1F/scripts.pory"
	release
	end


LittlerootHouse2_1F_Mother_Text_0:
# 8 "data/maps/LittlerootTown_House2_1F/scripts.pory"
	.string "Sometimes I wish we didn't have kids...$"
