LittlerootTown_House3_1F_MapScripts::
	.byte 0


LittlerootTown_House3_1F_Mother::
# 6 "data/maps/LittlerootTown_House3_1F/scripts.pory"
	lock
# 7 "data/maps/LittlerootTown_House3_1F/scripts.pory"
	msgbox LittlerootTown_House3_1F_Mother_Text_0
# 9 "data/maps/LittlerootTown_House3_1F/scripts.pory"
	release
	end


LittlerootTown_House3_1F_Mother_Text_0:
# 7 "data/maps/LittlerootTown_House3_1F/scripts.pory"
	.string "Let's see...\n"
	.string "I'll have to go to OLDALE for that,\l"
	.string "since the bridge to LITTLEROOT LAKE is\l"
	.string "out again...\n"
	.string "$"
