LittlerootLake_East_MapScripts::
	.byte 0


EastLakeFisher::
# 6 "data/maps/LittlerootLake_East/scripts.pory"
	lock
# 7 "data/maps/LittlerootLake_East/scripts.pory"
	faceplayer
# 8 "data/maps/LittlerootLake_East/scripts.pory"
	message EastLakeFisher_Text_0
# 9 "data/maps/LittlerootLake_East/scripts.pory"
	waitmessage
# 10 "data/maps/LittlerootLake_East/scripts.pory"
	release
	end


EastLakeFisher_Text_0:
# 8 "data/maps/LittlerootLake_East/scripts.pory"
	.string "The fish here are superb!$"
