LittlerootLake_House3_2F_MapScripts::
	.byte 0


LittlerootLakeHouse3_Man::
# 5 "data/maps/LittlerootLake_House3_2F/scripts.pory"
	lock
# 6 "data/maps/LittlerootLake_House3_2F/scripts.pory"
	faceplayer
# 7 "data/maps/LittlerootLake_House3_2F/scripts.pory"
	msgbox LittlerootLakeHouse3_Man_Text_0
# 8 "data/maps/LittlerootLake_House3_2F/scripts.pory"
	waitmessage
# 9 "data/maps/LittlerootLake_House3_2F/scripts.pory"
	release
	end


LittlerootLakeHouse3_Man_Text_0:
# 7 "data/maps/LittlerootLake_House3_2F/scripts.pory"
	.string "...Why are you in my house?$"
