LittlerootTown_House4_1F_MapScripts::
	.byte 0


Littleroot_House4_Zig::
# 6 "data/maps/LittlerootTown_House4_1F/scripts.pory"
	lock
# 7 "data/maps/LittlerootTown_House4_1F/scripts.pory"
	faceplayer
# 8 "data/maps/LittlerootTown_House4_1F/scripts.pory"
	msgbox Littleroot_House4_Zig_Text_0
# 9 "data/maps/LittlerootTown_House4_1F/scripts.pory"
	waitmessage
# 10 "data/maps/LittlerootTown_House4_1F/scripts.pory"
	release
	end


Littleroot_House4_Zig_Text_0:
# 8 "data/maps/LittlerootTown_House4_1F/scripts.pory"
	.string "Zig-a-zig-a-zig!$"
