Route125Addition_MapScripts::
	.byte 0


Route125_Bird_1::
# 6 "data/maps/Route125Addition/scripts.pory"
	lock
# 7 "data/maps/Route125Addition/scripts.pory"
	faceplayer
# 8 "data/maps/Route125Addition/scripts.pory"
	msgbox Route125_Bird_1_Text_0
# 9 "data/maps/Route125Addition/scripts.pory"
	waitmessage
# 10 "data/maps/Route125Addition/scripts.pory"
	release
	end


Route125_Bird_2::
# 15 "data/maps/Route125Addition/scripts.pory"
	lock
# 16 "data/maps/Route125Addition/scripts.pory"
	faceplayer
# 17 "data/maps/Route125Addition/scripts.pory"
	msgbox Route125_Bird_2_Text_0
# 18 "data/maps/Route125Addition/scripts.pory"
	waitmessage
# 19 "data/maps/Route125Addition/scripts.pory"
	release
	end


Route125_Bird_3::
# 24 "data/maps/Route125Addition/scripts.pory"
	lock
# 25 "data/maps/Route125Addition/scripts.pory"
	faceplayer
# 26 "data/maps/Route125Addition/scripts.pory"
	msgbox Route125_Bird_3_Text_0
# 27 "data/maps/Route125Addition/scripts.pory"
	waitmessage
# 28 "data/maps/Route125Addition/scripts.pory"
	release
	end


Route125_Skitty::
# 33 "data/maps/Route125Addition/scripts.pory"
	lock
# 34 "data/maps/Route125Addition/scripts.pory"
	faceplayer
# 35 "data/maps/Route125Addition/scripts.pory"
	msgbox Route125_Skitty_Text_0
# 36 "data/maps/Route125Addition/scripts.pory"
	waitmessage
# 37 "data/maps/Route125Addition/scripts.pory"
	release
	end


Route125_Azu::
# 42 "data/maps/Route125Addition/scripts.pory"
	lock
# 43 "data/maps/Route125Addition/scripts.pory"
	faceplayer
# 44 "data/maps/Route125Addition/scripts.pory"
	msgbox Route125_Azu_Text_0
# 45 "data/maps/Route125Addition/scripts.pory"
	waitmessage
# 46 "data/maps/Route125Addition/scripts.pory"
	release
	end


Route125_EventScript_Sign::
# 51 "data/maps/Route125Addition/scripts.pory"
	lock
# 52 "data/maps/Route125Addition/scripts.pory"
	msgbox Route125_EventScript_Sign_Text_0
# 53 "data/maps/Route125Addition/scripts.pory"
	release
	end


Route125_Bird_1_Text_0:
# 8 "data/maps/Route125Addition/scripts.pory"
	.string "Gull?$"

Route125_Bird_2_Text_0:
# 17 "data/maps/Route125Addition/scripts.pory"
	.string "Kwu?$"

Route125_Bird_3_Text_0:
# 26 "data/maps/Route125Addition/scripts.pory"
	.string "?$"

Route125_Skitty_Text_0:
# 35 "data/maps/Route125Addition/scripts.pory"
	.string "Mwao?$"

Route125_Azu_Text_0:
# 44 "data/maps/Route125Addition/scripts.pory"
	.string "Zu!$"

Route125_EventScript_Sign_Text_0:
# 52 "data/maps/Route125Addition/scripts.pory"
	.string "Mossdeep Commune./n“We don't have a\n"
	.string "motto.”$"
