LittlerootTown_House3_2F_MapScripts::
	.byte 0


LittlerootTown_House3_2F_Boy::
# 6 "data/maps/LittlerootTown_House3_2F/scripts.pory"
	lock
# 7 "data/maps/LittlerootTown_House3_2F/scripts.pory"
	faceplayer
# 8 "data/maps/LittlerootTown_House3_2F/scripts.pory"
	msgbox LittlerootTown_House3_2F_Boy_Text_0
# 9 "data/maps/LittlerootTown_House3_2F/scripts.pory"
	waitmessage
# 10 "data/maps/LittlerootTown_House3_2F/scripts.pory"
	release
	end


LittlerootTown_House3_2F_Boy_Text_0:
# 8 "data/maps/LittlerootTown_House3_2F/scripts.pory"
	.string "My dad is always just wandering around\n"
	.string "outside.$"
