LittlerootTown_House4_2F_MapScripts::
	.byte 0


Littleroot_House4_2F_Girl::
# 6 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	lock
# 7 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	faceplayer
# 8 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	msgbox Littleroot_House4_2F_Girl_Text_0
# 9 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	waitmessage
# 10 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	release
	end


Littleroot_House4_2F_Skitty::
# 15 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	lock
# 16 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	faceplayer
# 17 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	msgbox Littleroot_House4_2F_Skitty_Text_0
# 18 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	waitmessage
# 19 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	release
	end


Littleroot_House4_2F_Girl_Text_0:
# 8 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	.string "I love Pokémon!$"

Littleroot_House4_2F_Skitty_Text_0:
# 17 "data/maps/LittlerootTown_House4_2F/scripts.pory"
	.string "Skreeeow!$"
