LittlerootTown_House1_1F_MapScripts::
	.byte 0


LittlerootTown_House1_Man::
# 6 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	lock
# 7 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	faceplayer
# 8 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	msgbox LittlerootTown_House1_Man_Text_0
# 9 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	waitmessage
# 10 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	msgbox LittlerootTown_House1_Man_Text_1
# 11 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	waitmessage
# 12 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	release
	end


LittlerootTown_House1_Boy::
# 17 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	lock
# 18 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	faceplayer
# 19 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	msgbox LittlerootTown_House1_Boy_Text_0
# 20 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	waitmessage
# 21 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	release
	end


LittlerootTown_House1_Man_Text_0:
# 8 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	.string "I love to cook!$"

LittlerootTown_House1_Man_Text_1:
# 10 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	.string "I think I left my ORAN BERRY upstairs.$"

LittlerootTown_House1_Boy_Text_0:
# 19 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	.string "Daddy is a bad cook.$"
