LittlerootTown_House1_1F_MapScripts::
	.byte 0


LittlerootTown_House1_Man::
# 6 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	lock
# 7 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	faceplayer
# 8 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	msgbox LittlerootTown_House1_Man_Text_0
# 9 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	waitmessage
# 10 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	face_up
# 11 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	face_down
# 12 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	face_up
# 13 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	Face_left
# 14 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	face_up
# 15 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	msgbox LittlerootTown_House1_Man_Text_1
# 16 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	release
	end


LittlerootTown_House1_Boy::
# 21 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	lock
# 22 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	faceplayer
# 23 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	msgbox LittlerootTown_House1_Boy_Text_0
# 24 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	waitmessage
# 25 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	release
	end


LittlerootTown_House1_Man_Text_0:
# 8 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	.string "I love to cook!$"

LittlerootTown_House1_Man_Text_1:
# 15 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	.string "I think I left my ORAN BERRY upstairs.$"

LittlerootTown_House1_Boy_Text_0:
# 23 "data/maps/LittlerootTown_House1_1F/scripts.pory"
	.string "Daddy is a bad cook.$"
